### ISSUE TITLE
Cannot read property 'track' of undefined

### ISSUE THREAD

**Issue by rahulmukati** [WilliamDASILVA/nuxt-facebook-pixel-module#26]
No property of **this.$fb** is working after update to v1.4.0.
Not even default PageView is getting tracked.

**Comment by bigsee** [comment]
I have the same issue, although I experienced it before upgrading to v1.4.0. I tried to upgrade to 1.4.0 to fix the issue but it persists... the issue only appeared this evening after a deploy and was working fine up until then.

Anyone have any ideas?

**Comment by Haeresis** [comment]
Hello @WilliamDASILVA, I just try to use the package right now. Same issue.

From Nuxt Plugin with that

```
export default function ({ $fb }) {
   $fb.enable() // this return the following error
}
```

```
TypeError: Cannot read property 'enable' of undefined
    at eval (analytics.js?17c1:11)
    at _callee2$ (index.js?f26e:72)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
```

Same if I directly use it from Nuxt Layout for example

```
...
<script>
export default {
  ...
  mounted() {
    this.$fb.enable()
  },
  ...
...
</script>
...
```

```
TypeError: Cannot read property 'enable' of undefined
    at VueComponent.mounted (IklLogged.vue?7858:36)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at callHook (vue.runtime.esm.js?2b0e:4219)
    at Object.insert (vue.runtime.esm.js?2b0e:3139)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:6346)
    at Vue.patch [as __patch__] (vue.runtime.esm.js?2b0e:6494)
    at Vue._update (vue.runtime.esm.js?2b0e:3945)
    at Vue.updateComponent (vue.runtime.esm.js?2b0e:4060)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at new Watcher (vue.runtime.esm.js?2b0e:4468)
```

**Comment by Haeresis** [comment]
Maybe it's related with some @emaia improvement merge?

**Comment by Haeresis** [comment]
After looked inside the code I see this.

```
// Don't include when run in dev mode unless debug: true is configured
  if (this.options.dev && !options.debug) {
```

So I try to add the `debug` value inside config like this
```
  facebook: {
    track: 'PageView',
    pixelId: env.env_variables.FACEBOOK_PIXEL_ID,
    autoPageView: true,
    disabled: true,
    debug: true,
  },
```
And the function work.

So first change

```
$fb.enable()
// or
this.$fb.enable()
```

by

```
$fb && $fb.enable()
// or
this.$fb && this.$fb.enable()
```

I assume it will work in production.
To test it in your dev env, use

`debug: true`

In options from `nuxt.config.js`.

Hope that can help you @rahulmukati and @bigsee until the doc was improved to mention that.

**Comment by WilliamDASILVA** [comment]
Hello,

Thank you for opening the issue and thanks @Haeresis for the debugging!
I've updated the module to inject the `Fb` plugin even if the `debug` option is not specified. A console log message was also added & updated the README to clarify the `debug` usage.

This change has been released in v1.5.0. Sorry for the trouble.

**Comment by Haeresis** [comment]
Thank you so much for your work and your reactivity @WilliamDASILVA!

**Comment by bigsee** [comment]
@WilliamDASILVA awesome! Thank you for the fast response! :)

**Comment by Ziaurrahaman7** [comment]
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'facebook')
 
  at facebookPixelModule (node_modules\nuxt-facebook-pixel-module\lib\module.js:15:67)
  at installModule (/F:/laragon/www/tramedi_frontend/node_modules/@nuxt/kit/dist/index.mjs:440:101)
  at async initNuxt (/F:/laragon/www/tramedi_frontend/node_modules/nuxt/dist/index.mjs:2908:7)
  at async load (/F:/laragon/www/tramedi_frontend/node_modules/nuxi/dist/chunks/dev.mjs:201:9)
  at async Object.invoke (/F:/laragon/www/tramedi_frontend/node_modules/nuxi/dist/chunks/dev.mjs:245:5)
  at async _main (/F:/laragon/www/tramedi_frontend/node_modules/nuxi/dist/cli.mjs:48:20)
  my modules
    modules:[
    "@nuxtjs/tailwindcss",
    "nuxt-icon",
    "nuxt-swiper",
    'nuxt-facebook-pixel-module',

    // With options
    ['nuxt-facebook-pixel-module', {
      /* module options */
      track: 'PageView',
      pixelId: 'FACEBOOK_PIXEL_ID',
      autoPageView: true,
      disabled: false
    }],
  ],

**Comment by XHJeon** [comment]
Same as @Ziaurrahaman7
